name: doctor_appointments
description: A Flutter app for managing doctor appointments.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0              

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2     

flutter:
  uses-material-design: true
